# Generated by Django 4.2.7 on 2023-12-10 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0004_formcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedevent',
            name='event',
        ),
        migrations.AddField(
            model_name='likedevent',
            name='event_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='likedevent',
            name='event_city',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='likedevent',
            name='event_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
        ),
        migrations.AddField(
            model_name='likedevent',
            name='event_image',
            field=models.URLField(default='default_image_url'),
        ),
        migrations.AddField(
            model_name='likedevent',
            name='event_name',
            field=models.CharField(default='Unknown Event', max_length=255),
        ),
        migrations.AddField(
            model_name='likedevent',
            name='event_state',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='likedevent',
            name='event_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
        ),
        migrations.AddField(
            model_name='likedevent',
            name='event_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='likedevent',
            name='event_venue',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
